import { escapeHtml } from './sanitize.js';

const STORAGE_KEY = 'wank_records';

export function getLocalRecords() {
    try {
        return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
    } catch {
        return [];
    }
}

export function saveLocalRecords(records) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(records));
}

export function getCurrentMonthKey(date = new Date()) {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
}

export function formatDuration(ms, texts) {
    if (ms == null || ms < 0) return '—';
    const minutes = Math.floor(ms / 60000);
    const hours = Math.floor(minutes / 60);
    const days = Math.floor(hours / 24);

    if (days > 0) {
        const remainHours = hours % 24;
        return remainHours > 0
            ? `${days}${texts['unit-day'] || '天'} ${remainHours}${texts['unit-hour'] || '小時'}`
            : `${days}${texts['unit-day'] || '天'}`;
    }
    if (hours > 0) {
        const remainMinutes = minutes % 60;
        return remainMinutes > 0
            ? `${hours}${texts['unit-hour'] || '小時'} ${remainMinutes}${texts['unit-minute'] || '分鐘'}`
            : `${hours}${texts['unit-hour'] || '小時'}`;
    }
    if (minutes > 0) return `${minutes}${texts['unit-minute'] || '分鐘'}`;
    return texts['time-just-now'] || '剛剛';
}

export function computeStats(records = getLocalRecords()) {
    const sorted = [...records]
        .filter(r => r.time)
        .sort((a, b) => new Date(b.time) - new Date(a.time));

    const now = new Date();
    const monthKey = getCurrentMonthKey(now);
    const monthlyCount = sorted.filter(r => getCurrentMonthKey(new Date(r.time)) === monthKey).length;

    let sinceLast = null;
    if (sorted.length > 0) {
        sinceLast = now - new Date(sorted[0].time);
    }

    let avgInterval = null;
    let longestInterval = null;
    if (sorted.length >= 2) {
        const intervals = [];
        for (let i = 0; i < sorted.length - 1; i++) {
            const gap = new Date(sorted[i].time) - new Date(sorted[i + 1].time);
            if (gap > 0) intervals.push(gap);
        }
        if (intervals.length > 0) {
            avgInterval = intervals.reduce((a, b) => a + b, 0) / intervals.length;
            longestInterval = Math.max(...intervals);
        }
    }

    return { sorted, monthlyCount, sinceLast, avgInterval, longestInterval };
}

export function renderLocalStats() {
    const texts = window.getTexts ? window.getTexts() : {};
    const { sorted, monthlyCount, sinceLast, avgInterval } = computeStats();

    const sinceEl = document.getElementById('stat-since-value');
    const monthlyEl = document.getElementById('stat-monthly-value');
    const avgEl = document.getElementById('stat-avg-value');
    const list = document.getElementById('history-list');
    const emptyHint = document.getElementById('history-empty');

    if (sinceEl) sinceEl.textContent = sinceLast != null ? formatDuration(sinceLast, texts) : '—';
    if (monthlyEl) monthlyEl.textContent = String(monthlyCount);
    if (avgEl) avgEl.textContent = avgInterval != null ? formatDuration(avgInterval, texts) : '—';

    if (!list) return;

    const recent = sorted.slice(0, 10);
    if (recent.length === 0) {
        list.innerHTML = '';
        if (emptyHint) emptyHint.style.display = 'block';
        return;
    }

    if (emptyHint) emptyHint.style.display = 'none';
    list.innerHTML = recent.map(rec => {
        const dateObj = new Date(rec.time);
        const dateStr = `${dateObj.getFullYear()}/${String(dateObj.getMonth() + 1).padStart(2, '0')}/${String(dateObj.getDate()).padStart(2, '0')} ${String(dateObj.getHours()).padStart(2, '0')}:${String(dateObj.getMinutes()).padStart(2, '0')}`;
        const note = rec.note ? `<span class="history-note">${escapeHtml(rec.note)}</span>` : '';
        return `<li class="history-item"><span>${dateStr}${note ? ' · ' + note : ''}</span></li>`;
    }).join('');
}

export function updateShareCaptureArea() {
    const texts = window.getTexts ? window.getTexts() : {};
    const { monthlyCount, sinceLast, longestInterval } = computeStats();

    const setText = (id, value) => {
        const el = document.getElementById(id);
        if (el) el.textContent = value;
    };

    setText('share-label-monthly', texts['stat-monthly'] || '本月次數');
    setText('share-label-since', texts['stat-since'] || '距離上次');
    setText('share-label-longest', texts['stat-longest'] || '最長間隔');
    setText('share-value-monthly', String(monthlyCount));
    setText('share-value-since', sinceLast != null ? formatDuration(sinceLast, texts) : '—');
    setText('share-value-longest', longestInterval != null ? formatDuration(longestInterval, texts) : '—');
    setText('share-card-caption', texts['share-card-caption'] || '截圖已生成！');
    setText('share-generated-by', texts['share-generated-by'] || 'Generated by 打飛機紀錄');
}

window.renderLocalStats = renderLocalStats;
window.updateShareCaptureArea = updateShareCaptureArea;
window.computeStats = computeStats;
window.formatDuration = formatDuration;
